Database:
  Address: localhost
  Port: 3306
  Username: mcMMO
  Password: mcMMO
  Database: minecraft
  Prefix: mantle_

Banking:
  Money-Prefix: £
  Default-Balance: 500

Warps:
  Per-Page: 5

Groups:
  # If true then teams will be handled with the groups system.
  Use-Team-System: true
  Per-Page: 5

Chorus-Fruit:
  Replace-Teleport-With-Effects: true
  # The chances must add up to a value between 0 and 101
  # Chance is the %
  # Duration is in seconds
  Effects:
    'BLINDNESS':
      Chance: 25
      Duration: 5
      Amplifier: 1
    'HUNGER':
      Chance: 15
      Duration: 10
      Amplifier: 1
    'FAST_DIGGING':
      Chance: 20
      Duration: 30
      Amplifier: 1
    'FIRE_RESISTANCE':
      Chance: 20
      Duration: 30
      Amplifier: 1
    'INCREASE_DAMAGE':
      Chance: 10
      Duration: 15
      Amplifier: 1
    'HEALTH_BOOST':
      Chance: 5
      Duration: 15
      Amplifier: 1