name: Mantle
version: 1.0
author: Jack "Scarso" Farhall
main: gb.Jack.mantle.Mantle
api-version: 1.13
commands:
  bank:
    description: Allows access to your bank
  givehead:
    description: Gives you the player head specified
  warps:
    description: Lists all current warps
  reloadwarps:
    description: Reimports all warps from the database
  warp:
    description: Teleports you to a given warp location
  groups:
    description: Lists all active groups on the server
  group:
    description: Allows players to change, create and remove groups
permissions:
  mantle:
    description: Gives access to all commands within the FirstPlugin
    children:
      mantle.givehead: true
      mantle.warp: true
      mantle.group: true
  mantle.givehead:
    description: Allows access to the givehead releated commands
    default: false
    children:
      mantle.givehead.self: true
      mantle.givehead.others: true
      mantle.givehead.bypass: true
  mantle.givehead.self:
    description: Allows you to get your head
    default: false
  mantle.givehead.others:
    description: Allows you to get the head of other players
    default: false
  mantle.givehead.bypass:
    description: Allows you to bypass the cooldown between uses of the command
    default: false
  mantle.warp:
    description: Allows access to all warp commands
    default: false
    children:
      mantle.warp.action: true
      mantle.warp.list: true
      mantle.warp.reload: true
  mantle.warp.action:
    description: Allows you to warp yourself to different locations
    default: false
  mantle.warp.list:
    description: Allows you to use the /warps command to list all warps
    default: false
  mantle.warp.reload:
    description: Allows you to reload warps from the database
    default: false
  mantle.group:
    description: Allows access to all group commands
    default: false
    children:
      mantle.group.user: true
      mantle.group.manage: true
  mantle.group.user:
    description: Allows access to commands relating to being a member of a group
    default: false
    children:
      mantle.group.user.info: true
      mantle.group.user.join: true
      mantle.group.user.leave: true
      mantle.group.user.list: true
  mantle.group.user.info:
    description: Allows you to view information about your group
    default: false
  mantle.group.user.join:
    description: Allows you to join a group
    default: false
  mantle.group.user.leave:
    description: Allows you to leave your group
    default: false
  mantle.group.user.list:
    description: Allows you to list all active groups on the server
    default: false
  mantle.group.manage:
    description: Allows access to create, disband and modify a user's group
    default: false
    children:
      mantle.group.manage.create: true
      mantle.group.manage.disband: true
  mantle.group.manage.create:
    description: Allows the user to create a group
    default: false
  mantle.group.manage.disband:
    description: Allows the user to disband groups they own
    default: false